#!/bin/bash
#
# kolmnurk
# ülemine kolmnurk
#alumine kolmnurk
for ((r=4; r>0; r--))
do
        # veerud - tärnid
        for((t=1; t<$r ; t++))
        do
                echo -n "o "
        done

	for((t=1; t<$((4 - $r +2 )); t++))
        do
                echo -n "* "
	done
        echo #reavahetus
done

