#!/bin/bash
#
# kolmnurk
# ülemine kolmnurk
#alumine kolmnurk
echo -n "Sisesta ridade arv: "
read ridade_arv
for ((r=1; r<$(($ridade_arv + 1)); r++))
do
        # veerud - täpid
        for((t=1; t<$(($r + 1)); t++))
        do
                echo -n "o "
        done

	for((t=1; t<$(($ridade_arv - $r + 1 )); t++))
        do
                echo -n "* "
	done
        echo #reavahetus
done

