#!/bin/bash
#
# Keskkonna ja oma muutujate kasutamine
#
echo "Tere, $USER!"
#kuupäeva muutuse loomine
#defineerimine vastava väärtuse muutuja
kuupaev=`date +'%d. %B'`
echo "Täna on $kuupaev "
#kella väärtuse loomine
#defineerime vastava väärtusega muutuja
kell=`date +'%H:%M'`
#väljastame
echo "Kell on $kell"
kalender=`cal`
echo "Antud kuu kalender:"
echo "--------------------"
echo "$kalender"
echo "--------------------"
