#!/bin/bash
#
# arvu kontroll - positiivne või negatiivne
#
echo -n "Sisesta arv: "
read arv
#nüüd kontrollime, kas arv on positiivne
# sel juhul peab arv olema suure 0
if [ $arv -gt 0 ]
then
   # jah, arv on suurem kui 0 suurem positiivne
  echo "$arv on positiivne"
   # muidu kui arv ei ole suurem kui 0 siis negatiivne
else 
  echo "$arv on negatiivne"
# if lause tuleb korralikult lõpetada
fi
